### PR TITLE
To support debian

### PR DESCRIPTION
**Pull request by rzr**
Tested with device (thx)

### CODE REVIEW

**Comment by rzr** [comment]
I am considering to merge this is anyone against ?

**Comment by ganzziani** [comment]
I don't have a Linux environment to check this... what is it about? Just configuration to build on debian?

**Comment by rzr** [comment]
those are patches I created to make debian integration easier
there is no packaging files here

**Comment by rzr** [comment]
i can share docker files to replicate

**Comment by rzr** [comment]
Can't we specify for darwin ?

**Comment by HomeACcessoryKid** [comment]
I am not actually familiar with QT but can make experiments.
What exactly do you suggest gets changed?
Yet I am sceptical since it looks like macOS claims to be macx and unix at the same time...
How can I find out all the things that it claims to be?
And as a counter question, why do you have a line called "unix:"
can that not be turned into Linux:  ?

**Comment by rzr** [comment]
Please review:
https://github.com/ganzziani/xscopes-qt/pull/37

**Comment by HomeACcessoryKid** [comment]
see comment at #37

**Pull request merged**
